CREATE TABLE "public.USERS" (
	"email" TEXT(256) NOT NULL,
	"password" TEXT(256) NOT NULL,
	"name" TEXT(256) NOT NULL,
	"online" BOOLEAN NOT NULL,
	CONSTRAINT "USERS_pk" PRIMARY KEY ("email")
) WITH (
  OIDS=FALSE
);



CREATE TABLE "public.ROLES" (
	"name" TEXT NOT NULL,
	CONSTRAINT "ROLES_pk" PRIMARY KEY ("name")
) WITH (
  OIDS=FALSE
);



CREATE TABLE "public.USER_ROLES" (
	"user" TEXT NOT NULL,
	"role" TEXT NOT NULL,
	CONSTRAINT "USER_ROLES_pk" PRIMARY KEY ("user","role")
) WITH (
  OIDS=FALSE
);



CREATE TABLE "public.POSTS" (
	"user" TEXT NOT NULL,
	"text" TEXT NOT NULL,
	"type" TEXT NOT NULL,
	"time_posted" TIME NOT NULL,
	"id" serial NOT NULL,
	CONSTRAINT "POSTS_pk" PRIMARY KEY ("id")
) WITH (
  OIDS=FALSE
);



CREATE TABLE "public.USER_FRIENDS" (
	"user" TEXT NOT NULL,
	"friend" TEXT NOT NULL,
	CONSTRAINT "USER_FRIENDS_pk" PRIMARY KEY ("user","friend")
) WITH (
  OIDS=FALSE
);



CREATE TABLE "public.PWD_RESET_REQUESTS" (
	"user" TEXT NOT NULL,
	"url" TEXT NOT NULL UNIQUE,
	"time_created" TIME NOT NULL,
	"valid" BOOLEAN NOT NULL,
	"id" serial NOT NULL,
	CONSTRAINT "PWD_RESET_REQUESTS_pk" PRIMARY KEY ("id")
) WITH (
  OIDS=FALSE
);



CREATE TABLE "public.USER_REQUESTS" (
	"requester" TEXT NOT NULL,
	"target" TEXT NOT NULL,
	CONSTRAINT "USER_REQUESTS_pk" PRIMARY KEY ("requester","target")
) WITH (
  OIDS=FALSE
);



CREATE TABLE "public.USER_BLOCKED" (
	"user" TEXT NOT NULL,
	"blocked_user" TEXT NOT NULL,
	CONSTRAINT "USER_BLOCKED_pk" PRIMARY KEY ("user","blocked_user")
) WITH (
  OIDS=FALSE
);





ALTER TABLE "USER_ROLES" ADD CONSTRAINT "USER_ROLES_fk0" FOREIGN KEY ("user") REFERENCES "USERS"("email");
ALTER TABLE "USER_ROLES" ADD CONSTRAINT "USER_ROLES_fk1" FOREIGN KEY ("role") REFERENCES "ROLES"("name");

ALTER TABLE "POSTS" ADD CONSTRAINT "POSTS_fk0" FOREIGN KEY ("user") REFERENCES "USERS"("email");

ALTER TABLE "USER_FRIENDS" ADD CONSTRAINT "USER_FRIENDS_fk0" FOREIGN KEY ("user") REFERENCES "USERS"("email");
ALTER TABLE "USER_FRIENDS" ADD CONSTRAINT "USER_FRIENDS_fk1" FOREIGN KEY ("friend") REFERENCES "USERS"("email");

ALTER TABLE "PWD_RESET_REQUESTS" ADD CONSTRAINT "PWD_RESET_REQUESTS_fk0" FOREIGN KEY ("user") REFERENCES "USERS"("email");

ALTER TABLE "USER_REQUESTS" ADD CONSTRAINT "USER_REQUESTS_fk0" FOREIGN KEY ("requester") REFERENCES "USERS"("email");
ALTER TABLE "USER_REQUESTS" ADD CONSTRAINT "USER_REQUESTS_fk1" FOREIGN KEY ("target") REFERENCES "USERS"("email");

ALTER TABLE "USER_BLOCKED" ADD CONSTRAINT "USER_BLOCKED_fk0" FOREIGN KEY ("user") REFERENCES "USERS"("email");
ALTER TABLE "USER_BLOCKED" ADD CONSTRAINT "USER_BLOCKED_fk1" FOREIGN KEY ("blocked_user") REFERENCES "USERS"("email");









