CREATE TABLE USERS (
	email TEXT NOT NULL,
	password TEXT NOT NULL,
	name TEXT NOT NULL,
	online BOOLEAN NOT NULL,
	CONSTRAINT USERS_pk PRIMARY KEY (email)
) WITH (
  OIDS=FALSE
);



CREATE TABLE ROLES (
	name TEXT NOT NULL,
	id uuid NOT NULL,
	CONSTRAINT ROLES_pk PRIMARY KEY (id)
) WITH (
  OIDS=FALSE
);



CREATE TABLE USER_ROLE (
	user_email TEXT NOT NULL,
	role_id uuid NOT NULL,
	CONSTRAINT USER_ROLE_pk PRIMARY KEY (user_email,role_id)
) WITH (
  OIDS=FALSE
);



CREATE TABLE POST (
	user_email TEXT NOT NULL,
	text TEXT NOT NULL,
	time_posted TIME NOT NULL,
	id uuid NOT NULL,
	CONSTRAINT POST_pk PRIMARY KEY (id)
) WITH (
  OIDS=FALSE
);



CREATE TABLE USER_FRIEND (
	user_from TEXT NOT NULL,
	user_to TEXT NOT NULL,
	CONSTRAINT USER_FRIEND_pk PRIMARY KEY (user_from,user_to)
) WITH (
  OIDS=FALSE
);



CREATE TABLE USER_REQUEST (
	user_from TEXT NOT NULL,
	user_to TEXT NOT NULL,
	CONSTRAINT USER_REQUEST_pk PRIMARY KEY (user_from,user_to)
) WITH (
  OIDS=FALSE
);



CREATE TABLE USER_BLOCKED (
	user_blocker TEXT NOT NULL,
	user_blocked TEXT NOT NULL,
	CONSTRAINT USER_BLOCKED_pk PRIMARY KEY (user_blocker,user_blocked)
) WITH (
  OIDS=FALSE
);



CREATE TABLE TYPE (
	id uuid NOT NULL,
	name TEXT NOT NULL,
	CONSTRAINT TYPE_pk PRIMARY KEY (id)
) WITH (
  OIDS=FALSE
);



CREATE TABLE POST_TYPE (
	post_id uuid NOT NULL,
	type_id uuid NOT NULL,
	CONSTRAINT POST_TYPE_pk PRIMARY KEY (post_id,type_id)
) WITH (
  OIDS=FALSE
);

ALTER TABLE USER_ROLE ADD CONSTRAINT USER_ROLE_fk0 FOREIGN KEY (user_email) REFERENCES USERS(email);
ALTER TABLE USER_ROLE ADD CONSTRAINT USER_ROLE_fk1 FOREIGN KEY (role_id) REFERENCES ROLES(id);

ALTER TABLE POST ADD CONSTRAINT POST_fk0 FOREIGN KEY (user_email) REFERENCES USERS(email);

ALTER TABLE USER_FRIEND ADD CONSTRAINT USER_FRIEND_fk0 FOREIGN KEY (user_from) REFERENCES USERS(email);
ALTER TABLE USER_FRIEND ADD CONSTRAINT USER_FRIEND_fk1 FOREIGN KEY (user_to) REFERENCES USERS(email);

ALTER TABLE USER_REQUEST ADD CONSTRAINT USER_REQUEST_fk0 FOREIGN KEY (user_from) REFERENCES USERS(email);
ALTER TABLE USER_REQUEST ADD CONSTRAINT USER_REQUEST_fk1 FOREIGN KEY (user_to) REFERENCES USERS(email);

ALTER TABLE USER_BLOCKED ADD CONSTRAINT USER_BLOCKED_fk0 FOREIGN KEY (user_blocker) REFERENCES USERS(email);
ALTER TABLE USER_BLOCKED ADD CONSTRAINT USER_BLOCKED_fk1 FOREIGN KEY (user_blocked) REFERENCES USERS(email);


ALTER TABLE POST_TYPE ADD CONSTRAINT POST_TYPE_fk0 FOREIGN KEY (post_id) REFERENCES POST(id);
ALTER TABLE POST_TYPE ADD CONSTRAINT POST_TYPE_fk1 FOREIGN KEY (type_id) REFERENCES TYPE(id);





